# Generated by Django 2.0.9 on 2018-11-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_type',
            field=models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
