# Generated by Django 2.0.9 on 2018-12-04 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20181126_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='city',
            new_name='place',
        ),
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='app',
            name='last_editor',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='web_app_version',
            field=models.CharField(default=16, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='api',
            field=models.CharField(max_length=10, verbose_name='API Version'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_type',
            field=models.CharField(choices=[('Editor', 'Editor'), ('Viewer', 'Viewer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='app',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='app',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='app',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
