# Generated by Django 2.0.9 on 2018-12-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_app_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('Sewer System', 'Sewer System'), ('Power System', 'Power System')], max_length=100),
        ),
    ]
