# Generated by Django 2.0.9 on 2018-12-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20181204_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('Sewer System', 'Sewer System'), ('Power System', 'Power System'), ('Road System', 'Road System'), ('Tax Parcel', 'Tax Parcel'), ('Water System', 'Water System'), ('Zoning', 'Zoning')], max_length=100),
        ),
    ]
