# Generated by Django 2.0.9 on 2018-12-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20181204_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('SewerSystem', 'Sewer System'), ('PowerSystem', 'Power System'), ('RoadSystem', 'Road System'), ('TaxParcel', 'Tax Parcel'), ('WaterSystem', 'Water System'), ('Zoning', 'Zoning')], max_length=100),
        ),
    ]
