# Generated by Django 2.0.9 on 2018-12-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20181204_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_type',
            field=models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('SewerSystem', 'Sewer System'), ('PowerSystem', 'Power System'), ('RoadSystem', 'Road System'), ('TaxParcel', 'Tax Parcel'), ('WaterSystem', 'Water System'), ('Zoning', 'Zoning'), ('PavementManagement', 'Pavement Management')], max_length=100),
        ),
    ]
