# Generated by Django 2.0.9 on 2018-12-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20181204_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_type',
            field=models.CharField(choices=[('Editor', 'Editor'), ('Viewer', 'Viewer')], max_length=20),
        ),
    ]
