# Generated by Django 2.0.9 on 2018-12-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20181204_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='state',
            field=models.CharField(choices=[('AZ', 'AZ'), ('NV', 'NV'), ('SEI', 'SEI'), ('UT', 'UT'), ('WY', 'WY')], max_length=10),
        ),
    ]
