# Generated by Django 2.0.9 on 2018-12-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_auto_20181204_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('PavementManagement', 'Pavement Management'), ('PowerSystem', 'Power System'), ('SewerSystem', 'Sewer System'), ('RoadSystem', 'Road System'), ('TaxParcel', 'Tax Parcel'), ('WaterSystem', 'Water System'), ('Zoning', 'Zoning')], max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='place',
            field=models.CharField(choices=[('Afton', 'Afton'), ('BPDWWID', 'BPDWWID'), ('Caliente', 'Caliente'), ('ClarkCounty', 'Clark County'), ('LincolnCounty', 'Lincoln County'), ('MVWD', 'MVWD'), ('Minden', 'Minden'), ('PimaCounty', 'Pima County')], max_length=100),
        ),
    ]
