# Generated by Django 2.0.9 on 2018-12-05 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20181204_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='api',
            field=models.CharField(choices=[('3.26', '3.26'), ('4.9', '4.9')], max_length=10, verbose_name='API Version'),
        ),
        migrations.AlterField(
            model_name='app',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Last Edited'),
        ),
        migrations.AlterField(
            model_name='app',
            name='last_editor',
            field=models.CharField(max_length=100, verbose_name='Last Editor'),
        ),
    ]
