# Generated by Django 2.0.9 on 2018-12-05 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20181204_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='app',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
