# Generated by Django 2.0.9 on 2018-12-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_auto_20181204_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='last_editor',
            field=models.CharField(choices=[('BJ', 'Benjamin Cserepes'), ('CD', 'Christopher Daughton'), ('JH', 'Jarom Hlebasko'), ('JM', 'John McLaughlin'), ('RR', 'Rafal Rudzinski')], max_length=100, verbose_name='Last Editor'),
        ),
    ]
