# Generated by Django 2.0.9 on 2018-12-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20181204_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='place',
            field=models.CharField(choices=[('Afton', 'Afton'), ('BPDWWID', 'BPDWWID'), ('Caliente', 'Caliente'), ('ClarkCounty', 'Clark County'), ('LincolnCounty', 'Lincoln County'), ('MVWD', 'MVWD'), ('Minden', 'Minden'), ('PimaCounty', 'Pima County'), ('PineBluffs', 'Pine Bluffs')], max_length=100),
        ),
    ]
