# Generated by Django 2.0.9 on 2018-12-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_auto_20181204_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('PavementManagement', 'Pavement Management'), ('PowerSystem', 'Power System'), ('RoadSystem', 'Road System'), ('SewerSystem', 'Sewer System'), ('TaxParcel', 'Tax Parcel'), ('UtilitySystems', 'Utility Systems'), ('WaterSystem', 'Water System'), ('Zoning', 'Zoning')], max_length=100),
        ),
    ]
