# Generated by Django 2.0.9 on 2018-12-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_auto_20181218_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='place',
            field=models.CharField(choices=[('Afton', 'Afton'), ('Big Park', 'Big Park'), ('Caliente', 'Caliente'), ('Centerfield', 'Centerfield'), ('Clark County', 'Clark County'), ('Demo', 'Demo'), ('Lincoln County', 'Lincoln County'), ('MVWD', 'MVWD'), ('Minden', 'Minden'), ('Pima County', 'Pima County'), ('Pine Bluffs', 'Pine Bluffs')], max_length=100),
        ),
    ]
