# Generated by Django 2.0.9 on 2018-12-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_auto_20181218_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='place',
            field=models.CharField(choices=[('Afton', 'Afton'), ('Big Park', 'Big Park'), ('Caliente', 'Caliente'), ('Centerfield', 'Centerfield'), ('Clark County', 'Clark County'), ('Demo', 'Demo'), ('Enoch', 'Enoch'), ('Lincoln County', 'Lincoln County'), ('MVWD', 'MVWD'), ('Minden', 'Minden'), ('Pima County', 'Pima County'), ('Pine Bluffs', 'Pine Bluffs')], max_length=100),
        ),
    ]
