# Generated by Django 2.0.9 on 2019-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_auto_20190415_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='api',
            field=models.CharField(blank=True, choices=[('3.0', '3.0'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('3.5', '3.5'), ('3.6', '3.6'), ('3.7', '3.7'), ('3.8', '3.8'), ('3.9', '3.9'), ('3.10', '3.10'), ('3.11', '3.11'), ('3.12', '3.12'), ('3.13', '3.13'), ('3.14', '3.14'), ('3.15', '3.15'), ('3.16', '3.16'), ('3.17', '3.17'), ('3.18', '3.18'), ('3.19', '3.19'), ('3.21', '3.21'), ('3.22', '3.22'), ('3.23', '3.23'), ('3.24', '3.24'), ('3.27', '3.27'), ('4.0', '4.0'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('4.5', '4.5'), ('4.6', '4.6'), ('4.7', '4.7'), ('4.8', '4.8'), ('4.9', '4.9'), ('4.10', '4.10')], max_length=10, verbose_name='API Version'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_type',
            field=models.CharField(choices=[('Story', 'Story'), ('Template', 'Template'), ('WAB Editor', 'WAB Editor'), ('WAB Other', 'WAB Other'), ('WAB Viewer', 'WAB Viewer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('Accessibility Services', 'Accessibility Services'), ('Administrative Services', 'Administrative Services'), ('ArcGIS Online Services', 'ArcGIS Online Services'), ('Cemetery Services', 'Cemetery Services'), ('Data Collection Services', 'Data Collection Services'), ('Easement Services', 'Easement Services'), ('Economic Development Services', 'Economic Development Services'), ('Environmental Services', 'Environmental Services'), ('Event Services', 'Event Services'), ('General Services', 'General Services'), ('Mining Services', 'Mining Services'), ('Parcel/Addressing Services', 'Parcel/Addressing Services'), ('Recreational Services', 'Recreational Services'), ('Transportation Services', 'Transportation Services'), ('Utility System Services', 'Utility System Services'), ('Water Right Services', 'Water Right Services'), ('Zoning Services', 'Zoning Services')], max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='place',
            field=models.CharField(blank=True, choices=[('Afton WY', 'Afton WY'), ('Ashley Valley (UT) Water & Sewer District (AVWSID)', 'Ashley Valley (UT) Water & Sewer District (AVWSID)'), ('Bedford (WY) Water & Sewer District (BWSD)', 'Bedford (WY)  Water & Sewer District (BWSD)'), ('Big Park (AZ) Domestic Wastewater Improvement District (DWWID)', 'Big Park (AZ) Domestic Wastewater Improvement District (DWWID)'), ('Big Water UT', 'Big Water UT'), ('Caliente NV', 'Caliente NV'), ('Cedar Highlands UT', 'Cedar Highlands UT'), ('Centerfield UT', 'Centerfield UT'), ('Clark County NV', 'Clark County NV'), ('Cochise County AZ', 'Cochise County AZ'), ('Delta UT', 'Delta UT'), ('Demonstration (Demo)', 'Demonstration (Demo)'), ('Enoch UT', 'Enoch UT'), ('Fillmore UT', 'Fillmore UT'), ('Gila County AZ', 'Gila County AZ'), ('Greenlee County AZ', 'Greenlee County AZ'), ('Gunnison UT', 'Gunnison UT'), ('Hildale UT', 'Hildale UT'), ('Ivins UT', 'Ivins UT'), ('Johnson Water Improvement District (UT) (JWID)', 'Johnson Water Improvement District (UT) (JWID)'), ('Kane County (UT) Water Conservancy District (KCWCD)', 'Kane County (UT) Water Conservancy District (KCWCD)'), ('LaVerkin UT', 'LaVerkin UT'), ('Lincoln County NV', 'Lincoln County NV'), ('Manila UT', 'Manila UT'), ('Maricopa County AZ', 'Maricopa County AZ'), ('Mayfield UT', 'Mayfield UT'), ('Milford UT', 'Milford UT'), ('Minden NV', 'Minden NV'), ('Moapa Valley (NV) Water System (MVWD)', 'Moapa Valley (NV) Water System (MVWD)'), ('Mt. Pleasant UT', 'Mt. Pleasant UT'), ('Neola UT', 'Neola UT'), ('Parowan UT', 'Parowan UT'), ('Pima County AZ', 'Pima County AZ'), ('Pinal County AZ', 'Pinal County AZ'), ('Pine Bluffs WY', 'Pine Bluffs WY'), ('Rockville UT', 'Rockville UT'), ('Santa Clara UT', 'Santa Clara UT'), ('Southwest (UT) Mosquito Abatement Control District (SWMACD)', 'Southwest {UT) Mosquito Abatement Control District (SWMACD)'), ('Springdale UT', 'Springdale UT'), ('St George UT', 'St George UT'), ('Summit UT', 'Summit UT'), ('Thanksgiving Point UT', 'Thanksgiving Point UT'), ('Tridell Lapoint UT', 'Tridell Lapoint UT'), ('Tropic UT', 'Tropic UT'), ('Uintah County UT', 'Uintah County UT'), ('Vernal UT', 'Vernal UT'), ('Washington City UT', 'Washington City UT'), ('Washington County UT', 'Washington County UT'), ('Yuma County AZ', 'Yuma County AZ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='state',
            field=models.CharField(choices=[('AZ', 'AZ'), ('CA', 'CA'), ('CO', 'CO'), ('ID', 'ID'), ('NM', 'NM'), ('NV', 'NV'), ('OR', 'OR'), ('SEI', 'SEI'), ('UT', 'UT'), ('WA', 'WA'), ('WY', 'WY')], max_length=10),
        ),
    ]
