# Generated by Django 2.0.9 on 2019-05-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_auto_20190516_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='last_editor',
            field=models.CharField(choices=[('Benjamin Smith', 'Benjamin Smith'), ('Benjamin serepes', 'Benjamin serepes'), ('Christopher Daughton', 'Christopher Daughton'), ('Jarom Hlebasko', 'Jarom Hlebasko'), ('John McLaughlin', 'John McLaughlin'), ('Rafal Rudzinski', 'Rafal Rudzinski')], max_length=100, verbose_name='Last Editor'),
        ),
    ]
