# Generated by Django 2.0.9 on 2019-05-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0043_auto_20190522_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='web_app_version',
            field=models.CharField(blank=True, choices=[('1.3', '1.3'), ('1.4', '1.4'), ('2.0.1', '2.0.1'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('2.5', '2.5'), ('2.6', '2.6'), ('2.7', '2.7'), ('2.8', '2.8'), ('2.11', '2.11')], max_length=20),
        ),
    ]
