# Generated by Django 2.0.9 on 2019-05-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0048_auto_20190523_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='web_app_version',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('2.0', '2.0'), ('2.0.1', '2.0.1'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('2.4', '2.4'), ('2.5', '2.5'), ('2.6', '2.6'), ('2.7', '2.7'), ('2.8', '2.8'), ('2.9', '2.9'), ('2.10', '2.10'), ('2.11', '2.11'), ('2.12', '2.12')], max_length=20),
        ),
    ]
